module.exports = {
    'a': 'aaaaa',
    'b': 'aaaab',
    'c': 'aaaba',
    'd': 'aaabb',
    'e': 'aabaa',
    'f': 'aabab',
    'g': 'aabba',
    'h': 'aabbb',
    'i': 'abaaa',
    'j': 'abaab',
    'k': 'ababa',
    'l': 'ababb',
    'm': 'abbaa',
    'n': 'abbab',
    'o': 'abbba',
    'p': 'abbbb',
    'q': 'baaaa',
    'r': 'baaab',
    's': 'baaba',
    't': 'baabb',
    'u': 'babaa',
    'v': 'babab',
    'w': 'babba',
    'x': 'babbb',
    'y': 'bbaaa',
    'z': 'bbaab'
}